import ReactMarkdown, { type Components } from "react-markdown";
import remarkGfm from "remark-gfm";
import type { Citation, DebateTurn, Finding } from "@/lib/api";

// A paper-formatted version of the run. Hidden on screen (`print-only`), rendered
// only by the browser's print/"Save as PDF" dialog — so the dark war-room UI never
// bleeds into the document. Colours are set explicitly rather than inherited.
const MD: Components = {
  h2: ({ children }) => (
    <h2 className="mt-5 mb-2 border-b border-neutral-300 pb-1 text-[15px] font-bold text-black">
      {children}
    </h2>
  ),
  h3: ({ children }) => <h3 className="mt-3 mb-1 text-[13px] font-bold text-black">{children}</h3>,
  p: ({ children }) => <p className="mb-2 text-[11.5px] leading-relaxed text-neutral-800">{children}</p>,
  ul: ({ children }) => (
    <ul className="mb-2 list-disc space-y-1 pl-5 text-[11.5px] text-neutral-800">{children}</ul>
  ),
  li: ({ children }) => <li className="leading-relaxed">{children}</li>,
  strong: ({ children }) => <strong className="font-semibold text-black">{children}</strong>,
};

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-5 break-inside-avoid">
      <h2 className="mb-2 border-b border-neutral-300 pb-1 text-[13px] font-bold uppercase tracking-wider text-black">
        {title}
      </h2>
      {children}
    </section>
  );
}

export function PrintableReport({
  query,
  report,
  confidence,
  findings,
  uncertainties,
  citations,
  debate,
}: {
  query: string;
  report: string;
  confidence: number | null;
  findings: Finding[];
  uncertainties: string[];
  citations: Citation[];
  debate: DebateTurn[];
}) {
  const pct = confidence === null ? null : Math.round(confidence * 100);

  return (
    <div className="print-only bg-white p-0 text-black">
      {/* Masthead */}
      <header className="border-b-2 border-black pb-3">
        <p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-neutral-500">
          Atlas · Autonomous Due-Diligence Desk
        </p>
        <h1 className="mt-1 text-[20px] font-bold leading-tight text-black">{query}</h1>
        {pct !== null && (
          <p className="mt-2 text-[11px] text-neutral-700">
            Verdict confidence: <span className="font-bold text-black">{pct}%</span>
            <span className="text-neutral-500">
              {" "}
              — capped by citation coverage; every claim below is evidence-backed.
            </span>
          </p>
        )}
      </header>

      {/* The synthesized brief */}
      <div className="mt-4">
        <ReactMarkdown remarkPlugins={[remarkGfm]} components={MD}>
          {report}
        </ReactMarkdown>
      </div>

      {uncertainties?.length > 0 && (
        <Section title="What we're not sure about">
          <ul className="list-disc space-y-1 pl-5 text-[11.5px] text-neutral-800">
            {uncertainties.map((u, i) => (
              <li key={i}>{u}</li>
            ))}
          </ul>
        </Section>
      )}

      {findings?.length > 0 && (
        <Section title={`Findings (${findings.length})`}>
          <ul className="space-y-2">
            {findings.map((f, i) => (
              <li key={i} className="break-inside-avoid text-[11.5px] text-neutral-800">
                <span className="font-bold uppercase tracking-wide text-black">{f.agent}</span>
                <span className="text-neutral-500"> · conf {Math.round(f.confidence * 100)}%</span>
                <div>{f.claim}</div>
                {f.citation && f.citation !== "n/a" && (
                  <div className="text-[10px] italic text-neutral-500">Source: {f.citation}</div>
                )}
              </li>
            ))}
          </ul>
        </Section>
      )}

      {debate?.length > 0 && (
        <Section title="Bull vs Bear debate">
          <div className="space-y-2">
            {debate.map((d, i) => (
              <div key={i} className="break-inside-avoid text-[11.5px] text-neutral-800">
                <span className="font-bold uppercase tracking-wide text-black">{d.role}</span>
                {d.leaning && <span className="text-neutral-500"> · leaning: {d.leaning}</span>}
                <div>{d.text}</div>
              </div>
            ))}
          </div>
        </Section>
      )}

      {citations?.length > 0 && (
        <Section title="Sources">
          <ol className="list-decimal space-y-1 pl-5 text-[10.5px] text-neutral-700">
            {citations.map((c, i) => (
              <li key={i}>{c.citation}</li>
            ))}
          </ol>
        </Section>
      )}

      <footer className="mt-6 border-t border-neutral-300 pt-2 text-[9.5px] text-neutral-500">
        Generated by Atlas — a multi-agent research system. Claims are grounded in the cited
        evidence above; confidence is capped by citation coverage.
      </footer>
    </div>
  );
}
